import React from "react";
import { HugeiconsIcon } from "@hugeicons/react-native";
import {
  Activity01Icon,
  Alert01Icon,
  AlertCircleIcon,
  AppsIcon,
  ArrowDown01Icon,
  ArrowDownLeft01Icon,
  ArrowDownRight01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowUpLeft01Icon,
  ArrowUpRight01Icon,
  Attachment01Icon,
  Award01Icon,
  BarChart02Icon,
  Briefcase01Icon,
  Building03Icon,
  Calendar01Icon,
  Camera01Icon,
  Cancel01Icon,
  CancelCircleIcon,
  Clock01Icon,
  CloudUploadIcon,
  Coffee01Icon,
  CompassIcon,
  Copy01Icon,
  CreditCardIcon,
  Delete01Icon,
  DollarSquareIcon,
  FavouriteIcon,
  File01Icon,
  FilterIcon,
  Folder01Icon,
  FolderAddIcon,
  GiftIcon,
  GridIcon,
  HashtagIcon,
  HelpCircleIcon,
  Home01Icon,
  Image01Icon,
  InformationIcon,
  Invoice01Icon,
  Key01Icon,
  LifebuoyIcon,
  Link01Icon,
  LinkSquare01Icon,
  Location01Icon,
  LockIcon,
  Login01Icon,
  Logout01Icon,
  Mail01Icon,
  MapIcon,
  Message01Icon,
  Message02Icon,
  Microphone01Icon,
  MinusSignIcon,
  Moon02Icon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  NavigationIcon,
  Notification01Icon,
  PackageIcon,
  PauseIcon,
  PencilIcon,
  PieChartIcon,
  PlayIcon,
  PlusSignCircleIcon,
  PlusSignIcon,
  RadioIcon,
  RefreshIcon,
  Save01Icon,
  Search01Icon,
  Send01Icon,
  Settings01Icon,
  Share01Icon,
  Shield01Icon,
  ShoppingBag01Icon,
  SlidersHorizontalIcon,
  SmartPhone01Icon,
  StarIcon,
  Store01Icon,
  Sun01Icon,
  Tag01Icon,
  Tick01Icon,
  TickCircleIcon,
  Ticket01Icon,
  Truck01Icon,
  UserGroupIcon,
  UserIcon,
  Video01Icon,
  ViewIcon,
  ViewOffIcon,
  Wallet01Icon,
  Wifi01Icon,
  ZapIcon,
} from "@hugeicons/core-free-icons";
import { ViewStyle } from "react-native";

export type IconName = string;

export interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  style?: ViewStyle;
}

const iconMap: Record<string, any> = {
  "arrow-left": ArrowLeft01Icon,
  "map-pin": Location01Icon,
  x: Cancel01Icon,
  navigation: NavigationIcon,
  truck: Truck01Icon,
  "message-square": Message01Icon,
  plus: PlusSignIcon,
  "trash-2": Delete01Icon,
  "alert-circle": AlertCircleIcon,
  "check-circle": TickCircleIcon,
  image: Image01Icon,
  "shopping-bag": ShoppingBag01Icon,
  heart: FavouriteIcon,
  "message-circle": Message02Icon,
  "share-2": Share01Icon,
  user: UserIcon,
  minus: MinusSignIcon,
  phone: SmartPhone01Icon,
  "help-circle": HelpCircleIcon,
  "credit-card": CreditCardIcon,
  lock: LockIcon,
  info: InformationIcon,
  home: Home01Icon,
  grid: GridIcon,
  "dollar-sign": DollarSquareIcon,
  sliders: SlidersHorizontalIcon,
  tag: Tag01Icon,
  send: Send01Icon,
  "file-text": Invoice01Icon,
  search: Search01Icon,
  store: Store01Icon,
  star: StarIcon,
  settings: Settings01Icon,
  "log-out": Logout01Icon,
  bell: Notification01Icon,
  "chevron-right": ArrowRight01Icon,
  "chevron-left": ArrowLeft01Icon,
  "chevron-down": ArrowDown01Icon,
  "chevron-up": ArrowUp01Icon,
  "edit-2": PencilIcon,
  edit: PencilIcon,
  camera: Camera01Icon,
  check: Tick01Icon,
  copy: Copy01Icon,
  "external-link": LinkSquare01Icon,
  "more-vertical": MoreVerticalIcon,
  "more-horizontal": MoreHorizontalIcon,
  filter: FilterIcon,
  calendar: Calendar01Icon,
  clock: Clock01Icon,
  map: MapIcon,
  compass: CompassIcon,
  play: PlayIcon,
  pause: PauseIcon,
  video: Video01Icon,
  mic: Microphone01Icon,
  link: Link01Icon,
  mail: Mail01Icon,
  eye: ViewIcon,
  "eye-off": ViewOffIcon,
  shield: Shield01Icon,
  zap: ZapIcon,
  "trending-up": ArrowUpRight01Icon,
  "trending-down": ArrowDownRight01Icon,
  briefcase: Briefcase01Icon,
  award: Award01Icon,
  "pie-chart": PieChartIcon,
  "bar-chart-2": BarChart02Icon,
  activity: Activity01Icon,
  users: UserGroupIcon,
  moon: Moon02Icon,
  sun: Sun01Icon,
  building: Building03Icon,
  paperclip: Attachment01Icon,
  "log-in": Login01Icon,
  delete: Delete01Icon,
  save: Save01Icon,
  "ticket-percent": Ticket01Icon,
  "arrow-right": ArrowRight01Icon,
  "life-buoy": LifebuoyIcon,
  wifi: Wifi01Icon,
  banknote: DollarSquareIcon,
  package: PackageIcon,
  "upload-cloud": CloudUploadIcon,
  gift: GiftIcon,
  folder: Folder01Icon,
  "alert-triangle": Alert01Icon,
  key: Key01Icon,
  hash: HashtagIcon,
  "folder-plus": FolderAddIcon,
  coffee: Coffee01Icon,
  Heart: FavouriteIcon,
  "arrow-up-left": ArrowUpLeft01Icon,
  smartphone: SmartPhone01Icon,
  "corner-down-right": ArrowDownRight01Icon,
  radio: RadioIcon,
  "arrow-down-left": ArrowDownLeft01Icon,
  file: File01Icon,
  "edit-3": PencilIcon,
  "refresh-cw": RefreshIcon,
  "x-circle": CancelCircleIcon,
  wallet: Wallet01Icon,
  "plus-circle": PlusSignCircleIcon,
  apps: AppsIcon,
};

export function Icon({ name, size = 24, color = "#0f172a", style }: IconProps) {
  const IconComponent = iconMap[name] || iconMap[name.toLowerCase()] || iconMap["apps"] || null;
  if (!IconComponent) return null;
  return <HugeiconsIcon icon={IconComponent} size={size} color={color} style={style as any} />;
}
